"use strict";
var _1 = require("../src/");
var date = new _1["default"]().get('date');
console.log(date);
var day = new _1["default"]().get('day');
console.log(day);
var cur = _1["default"].format('yyyy-MM-dd hh:mm:ss', new Date());
console.log(cur);
var last = new _1["default"]().prev('month').format();
console.log(last);
var prev = new _1["default"]().prev('month').fromNow();
console.log(prev);
console.log(new _1["default"]().prev('year').next('month').format());
console.log(new _1["default"]().prev('year').prev('month').countDays());
console.log(new _1["default"]().prev('month').next('month').next('date').isToday());
var next = new _1["default"]().next('month').next('date', 2).fromNow();
console.log(next);
var startOfYear = new _1["default"]().startOf('year');
console.log(startOfYear);
var startOfSeason = new _1["default"]().next('month').startOf('season');
console.log(startOfSeason);
var startOfMonth = new _1["default"]().startOf('month');
console.log(startOfMonth);
var startOfWeek = new _1["default"]().startOf('week');
console.log(startOfWeek);
var startOfDay = new _1["default"]().startOf('date');
console.log(startOfDay);
var startOfHour = new _1["default"]().startOf('hour');
console.log(startOfHour);
var startOfMinute = new _1["default"]().startOf('minute');
console.log(startOfMinute);
var settingDate = new _1["default"]().set('year', 1999).format();
console.log(settingDate);
//# sourceMappingURL=moment.js.map